# Generated by Django 2.2.1 on 2020-12-15 18:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('tsync_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=256)),
                ('phone', models.TextField()),
                ('full_address', models.TextField()),
                ('name_of_university', models.TextField()),
                ('graduation_year', models.IntegerField()),
                ('cgpa', models.FloatField()),
                ('experience_in_months', models.IntegerField()),
                ('current_work_place_name', models.TextField()),
                ('applying_in', models.TextField()),
                ('expected_salary', models.IntegerField()),
                ('field_buzz_reference', models.TextField()),
                ('github_project_url', models.URLField(max_length=512)),
                ('cv_file', models.FileField(upload_to='uploads/')),
                ('on_spot_update_time', models.DateTimeField(auto_now=True)),
                ('on_spot_creation_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
