# Generated by Django 2.2.1 on 2020-12-15 18:36

from django.db import migrations
import unixtimestampfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='on_spot_creation_time',
            field=unixtimestampfield.fields.UnixTimeStampField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='on_spot_update_time',
            field=unixtimestampfield.fields.UnixTimeStampField(auto_now=True),
        ),
    ]
