# Generated by Django 2.2.1 on 2020-12-16 09:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0002_auto_20201216_0036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('tsync_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
        ),
    ]
