# Generated by Django 2.2.1 on 2020-12-16 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0003_resume'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
